### ISSUE TITLE
data source not working in 6.7.X version of grafana

### ISSUE THREAD

**Issue by vmanju123** [optimizca/servicenow-grafana#25]
Hi

we followed all the steps
post installing the plugin in grafana when we launch data sources grafana crashes
we are using 6.7.X version of grafana

thanks
manjunath

**Comment by R2DToo** [comment]
Hello and thank you for your interest in our plugin.

It seems you are using a very old version of Grafana which we do not support.
We recommend you download the latest version of Grafana and our plugin in order for our plugin to operate correctly in addition to getting all the latest features and security updates for Grafana itself.
https://grafana.com/grafana/download
https://github.com/optimizca/servicenow-grafana/releases/tag/v1.6.5

However if you are not interested in the latest version of Grafana, the minimum version of Grafana which we support today is v9.2.20.

Thanks,
Braden

**Comment by R2DToo** [comment]
I'm going to proceed with closing this issue as this is a version compatibility issue with Grafana. 

If you have further issues we will be happy to investigate them.
Thanks,
Braden
