### ISSUE TITLE
Any Update on getting into the ServiceNow Store?

### ISSUE THREAD

**Issue by jHumeLPL** [optimizca/servicenow-grafana#31]
I know an Issue may not be the appropriate place to put this, but didn't know where else to ask it.

I'm really impressed with this plugin (the "Official" ServiceNow data source plugin for Grafana is pretty bare bones and a real pain to work with).  This plugin on the other hand looks incredible.  The biggest issue is that there's no way our ServiceNow team will let us install an app that isn't from the app store in our Production ServiceNow instance.

Are you relatively close to getting it into the Store?  If so, then I'm sure I can get it into our Dev ServiceNow instance and install the plugin in our Grafana environment for now to get a feel for it and start working on familiarizing myself with the plugin so that, when it does officially release in the SNOW Store, I can fast track getting it into our production instance.

Honestly, if this plugin works as good as it looks, you could charge for it.  The dashboards alone are worth money!

**Comment by R2DToo** [comment]
Hello,

Thank you for your interest in our plugin! We are currently working with the ServiceNow Application certification team for a technical review to be completed. All other reviews prior to launching into the ServiceNow Store are complete so once the technical review has been completed we will be in the store a few days later. I would estimate we are looking at 2-4 weeks and will post an update to the repo and this issue once that is finalized.

Thanks again for your interest and we hope to provide you an awesome plugin in the near future!

**Comment by R2DToo** [comment]
Hello @jHumeLPL,

I am pleased to announce our official release to the ServiceNow store!
You can find the ITOM Grafana Plugin in the store at this link: [https://store.servicenow.com/sn_appstore_store.do#!/store/application/c9d5fc3a1bf08990ba4d15c61a4bcb03/1.8.0](https://store.servicenow.com/sn_appstore_store.do#!/store/application/c9d5fc3a1bf08990ba4d15c61a4bcb03/1.8.0)

I will proceed to close this issue now but do not hesitate to create a new issue if one arises.
